# Use the official Python image from the Docker Hub
#FROM python:3.10-slim
FROM --platform=linux/amd64 python:3.10-slim

# Install Jupyter Lab and OpenSSH server
RUN apt-get update && \
    apt-get install -y --no-install-recommends openssh-server && \
    pip install --no-cache-dir jupyterlab

# Set up SSH directory and permissions
RUN mkdir /var/run/sshd && \
    echo 'root:root' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

# Expose the SSH and Jupyter ports
EXPOSE 22 8888

# Copy over the configuration file for Jupyter (if you have one, otherwise this line can be omitted)
#COPY jupyter_notebook_config.py ./

#RUN mkdir -p /Scripts

# Copy startup script
#COPY start.sh /Scripts

RUN echo about to ls
RUN ls -la


WORKDIR /app

#RUN echo about to ls
#RUN ls -la
#RUN echo finished ls
#RUN chmod +x start.sh

# Start SSH and Jupyter via the startup script
CMD ["../docker/start.sh"]

